[package]
name = "finder"
version = "0.1.0"
authors = ["Seb Glazebrook <sebastian.glazebrook@redbubble.com>"]

[lib]
name = "finder"
path = "src/lib.rs"

[dependencies]

clap = { version = ">=2.11.2", features = ["yaml"] }
